### ISSUE TITLE
Importing big repository slow  

### ISSUE THREAD

**Issue by teodortalov** [mantisbt-plugins/source-integration#200] opened 2017-03-07 07:28 UTC
Hello, I am using v2.0.1, but I have a problem importing big repositories. It takes a very long time and eventually dies, but sometimes it will import repository partially. 

Basically, I find this unreliable and I was wondering if there is a way / guidance as to how to go about importing big repositories, I want to make this more reliable, so if anybody else has had smiliar problem, please drop a line.

[Here is a smilier issue I found](https://github.com/mantisbt-plugins/source-integration/issues/60)

**Comment by dregad** [comment] 2017-03-07 09:40
Yes this is a known problem with the way the import script is written. Unfortunately I do not have the time to look into it. 

As a workaround, I believe you should be able to fully import a large repository by repeating operation several times after each timeout, as the script should pick things up where it left off.

I will close this as duplicate of #60 as this is essentially the same root cause.

**Closed by dregad** 2017-03-07 09:40 UTC
