### ISSUE TITLE
Basic-Auth plugin incompatibility?

### ISSUE THREAD

**Issue by palevi67** [mantisbt-plugins/source-integration#316] opened 2019-07-01 18:30 UTC
Hi, all

When I use vanilla MantisBT, I can import changes without problems:

```
php-cgi -f plugin.php page=Source/import id=all api_key=111......
Requesting svn log for Milenio starting with revision 22497...
Processing svn log (xml)...
Parsed to revision 22549.
Next lookup revision (22550) exceeds head revision (22549), skipping...
```
But if I activate this plugin: https://github.com/davewood/mantis-basic-auth
This is what I get:
```
APPLICATION ERROR #805
The username is invalid. Usernames may only contain Latin letters, numbers, spaces, hyphens, dots, plus signs and underscores ....
```

I'm not sure if this is the right place to ask, or better ask to basic-auth plugin authors ...

Any help appreciated!

**Comment by dregad** [comment] 2019-07-02 06:41
Hello

Considering that the mantis-basic-auth plugin is indicated to be *experimental*, and that a similar issue davewood/mantis-basic-auth#3 has already been reported, I'm inclined to say that the issue is on their side.

I'm going to close this for now, but feel free to reopen the issue with additional information, if you can provide additional information demonstrating that the error is triggered by source-integration.

**Closed by dregad** 2019-07-02 06:41 UTC
Labels: no change required
