### ISSUE TITLE
Set up questions?

### ISSUE THREAD

**Issue by TimLiGood** [mantisbt-plugins/source-integration#408] opened 2023-05-09 07:50 UTC
After the installation is complete, the following problems appear, how can I solve them?
![image](https://user-images.githubusercontent.com/132968931/236980013-90100b9e-7144-4029-bc6b-2dd8ec672517.png)

Information & Set
![image](https://user-images.githubusercontent.com/132968931/236980612-80b1692a-fc75-49f9-be65-2ea7537d327e.png)
![image](https://user-images.githubusercontent.com/132968931/236980659-082db005-a260-43dd-ad98-e096a6d8d838.png)
![mantis1](https://user-images.githubusercontent.com/132968931/237028785-cfcb7670-a3a3-469b-a079-18aa4d3ca451.png)
![image](https://user-images.githubusercontent.com/132968931/237029187-b2942321-b4ae-40a7-81bb-9b8345e1b44a.png)

GitLab
![image](https://user-images.githubusercontent.com/132968931/237031405-03ab8eb2-bfe6-46c2-95d3-ec237eff2fc2.png)
![image](https://user-images.githubusercontent.com/132968931/237029436-bf9ff680-5762-4337-bc05-88273bd82c4d.png)
![image](https://user-images.githubusercontent.com/132968931/237029714-0d64eafa-97fb-4d1b-8636-9490aa4ed63b.png)

**Comment by dregad** [comment] 2023-05-09 12:24
Sorry I do not use Gitlab myself, so all I can provide is some generic information. 

> ![image](https://user-images.githubusercontent.com/132968931/236980013-90100b9e-7144-4029-bc6b-2dd8ec672517.png)

This error occurs when the plugin is not able to retrieve JSON data from the Gitlab API at the given URL. (i.e. MantisBT API call json_url() returns null. This can happen for many reasons, and unfortunately there is no good logging or error handling in this part of the code.

The problem is most likely caused by your plugin configuration, installation or environment, and not a bug of the plugin. so I'm closing this Issue.

⚠️ you may want to generate a new access token, as you've published it in clear in your screenshot.

**Closed by dregad** 2023-05-09 12:24 UTC
Labels: GitLab, question
