### ISSUE TITLE
No email following svn commit

### ISSUE THREAD

**Issue by Postgre** [mantisbt-plugins/source-integration#195] opened 2017-01-25 15:16 UTC
No email following svn commit

**Comment by dregad** [comment] 2017-01-25 16:09
You are not providing any useful information that would allow understanding, let alone resolving the issue.

I do not use the SVN plugin myself, but to my knowledge, the source integration plugin does not send any emails. All it does is register the changeset (commit), and depending on configuration, take action on referenced MantisBT issues (e.g. resolve them) which in turn may trigger e-mail notifications..

**Comment by Postgre** [comment] 2017-01-27 17:43
Hello dregad,
Sorry for the delayed response
Without the SVN plugin, when I change the status of a bug, resolved for example, a notification email will be sent, but when I change the status via SVN plugin no mail
Thanks and have a nice time

**Comment by bright-tools** [comment] 2017-01-27 18:34
This sounds like it might be related (or same as) #22

**Comment by dregad** [comment] 2017-05-05 13:42
Resolving this as duplicate of #22

**Closed by dregad** 2017-05-05 13:42 UTC
Labels: duplicate
