### ISSUE TITLE
SourceCgit and 1.3.0: #1048: Column 'revision' cannot be null [...]

### ISSUE THREAD

**Issue by kierun** [mantisbt-plugins/source-integration#165] opened 2016-07-14 08:39 UTC
I am trying to get this plugin to work with 1.3.0.  I copied the Souce and SourceCgit directories and modified the SourceCgit so that it accepts 1.30 as a dependency.

However, when I try to import all the data from a cgit repository, I get this error:

```
Database query failed. Error received from database was #1048: Column 'revision' cannot be null for the query: INSERT INTO mantis_plugin_Source_changeset_table ( repo_id, revision, parent, branch, user_id,
timestamp, author, message, info, ported, author_email, committer, committer_email, committer_id
) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ).
```

Any idea what I am doing wrong?

It is possible that the database is in a dirty state but I am not confident enough to just delete random tables just on the off chance.

**Comment by morgant** [comment] 2016-07-14 12:30
I'm not sure if Cgit has been tested on 1.3.0 yet since the final version was just released, but let's knock out an easy question first: did you check out the `master-1.3x` branch?

**Comment by kierun** [comment] 2016-07-14 12:40
Yes, I did. Sorry, should have mentioned that. ☺

**Comment by dregad** [comment] 2016-08-03 11:29
@kierun sorry I do not use Cgit so it will be difficult for me to help.

I suggest in your Mantis config_inc.php, to set `$g_show_detailed_errors = ON;` and reproduce the error so we have a bit of context for the error (stack trace and the values of the query parameters).

**Comment by wadefelix** [comment] 2016-12-09 03:48
Does your cgit need a login? If It is, make sure your urls include the username and password. as `http://user:pswd@cgitserver/xxx.git`

**Comment by dregad** [comment] 2017-01-04 16:35
Close this for now. Feel free to reopen it if you can provide information to help reproduce the problem.

**Closed by dregad** 2017-01-04 16:35 UTC
Labels: can't reproduce

**Comment by dregad** [comment] 2021-12-30 15:28
Marking this as duplicate of #149
