### ISSUE TITLE
MantisBT version 2.20.0 + MantisBT Core v2.0.1 not Compatible

### ISSUE THREAD

**Issue by swimchiu** [mantisbt-plugins/source-integration#312] opened 2019-05-09 05:49 UTC
MantisBT version 2.20.0 + MantisBT Core v2.0.1 not Compatible.
Thanks.

I get the following message after clicked the Upgrade button:

> APPLICATION ERROR #2503
> 
> Upgrading the plugin schema failed in block #15.
> 
> Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

**Comment by swimchiu** [comment] 2019-05-09 05:59
![Screen Shot 2019-05-09 at 13 26 06](https://user-images.githubusercontent.com/8790220/57430545-a610ef80-7262-11e9-849b-5538f3a0e46a.png)

**Comment by swimchiu** [comment] 2019-05-09 05:59
<img width="1276" alt="Screen Shot 2019-05-09 at 13 38 29" src="https://user-images.githubusercontent.com/8790220/57430560-b32dde80-7262-11e9-8fb1-fe673ab9c01d.png">

**Comment by dregad** [comment] 2019-05-09 07:55
That's strange, the plugin's schema has not changed since v0.16.3 (2010 !)... What version of Source Control Integration are you upgrading from ?

Is there a `pvm_version_id` column in the `mantis_branch_table` in your DB ?

**Comment by dregad** [comment] 2019-05-09 16:12
@swimchiu you might want to have a look at mantisbt/mantisbt#1511, which improves the error message when plugin schema upgrade fails with details about the actual error and the offending SQL. 

If you could test that and provide feedback, it would be appreciated.

**Comment by swimchiu** [comment] 2019-05-21 06:00
@dregad Thanks for your reply. I will check the DB Table Info.

**Comment by dregad** [comment] 2019-05-24 15:10
@swimchiu did you get a chance to test the plugin upgrade using the improved code in above-mentioned pull request ?

**Comment by dregad** [comment] 2019-05-29 13:29
@swimchiu since you have not provided any feedback, and considering that I'm not able to reproduce the problem, I assume it is something specific to your environment or database, and I will close this issue.

For the record, mantisbt/mantisbt#1511 has been merged and will be included in upcoming MantisBT release 2.22.0.

**Closed by dregad** 2019-05-29 13:29 UTC
