### ISSUE TITLE
Retrieving master ... failed.

### ISSUE THREAD

**Issue by clan-destina** [mantisbt-plugins/source-integration#288] opened 2019-01-22 17:07 UTC
Hello,
I have the plugin working for 5+ month and suddenly I  get "Retrieving master ... failed."

I have not made any changes to Mantis or the Plugin.

I there a way to debug this error?

**Comment by dregad** [comment] 2019-01-25 08:06
@clan-destina Unfortunately, the plugin's logging / debugging capabilities are very limited (improving that is already planned see #92) so troubleshooting errors is always a bit of a pain; you may have to trace the error in the code. 

Since you did not provide any details about your setup (in particular which integration plugin you're using), I'm afraid can't really help much more than that. It could be caused by a failure to connect to the repository, or an invalid payload.

**Comment by dregad** [comment] 2019-01-28 11:09
Closing this for now. Feel free to reopen if needed.

**Closed by dregad** 2019-01-28 11:09 UTC
Labels: can't reproduce, question
